---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no

  tasks:
          - name: Add List of User on Nodes
            user: name="{{item}}" state=present
            with_items:
                    - raj
                    - simran
                    - prem_chopra
                    - nishadholakia

