---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
          pkgname: httpd

  tasks:
          - name: Install HTTPD Package
            action: yum name="{{pkgname}}" state=present
